# .air.toml — Splitter live reload config

# Path setup
root = "."
tmp_dir = ".air/tmp"
testdata_dir = ".testdata"

[build]
  # Where to build the binary
  bin = ".air/tmp/splitter"
  cmd = "go build -o .air/tmp/splitter ./cmd/server"

  # Rebuild debounce (milliseconds)
  delay = 500

  # Watch extensions and folders
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "migrations", "docker", ".air"]

  # Don’t rerun on unchanged files
  exclude_unchanged = true

  # Optional pre/post build commands
  pre_cmd = []
  post_cmd = []

  # Stop or continue on build errors
  stop_on_error = false

  # Log build errors
  log = ".air/build-errors.log"

[color]
  app = "cyan"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "blue"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false
