version: "3"

tasks:
  db:up:
    desc: Run Postgres via Docker
    cmds:
      - docker compose up -d postgres

  db:down:
    desc: Stop and remove Postgres container
    cmds:
      - docker compose down

  build:
    desc: Build the binary
    cmds:
      - go build -o bin/splitter ./cmd/server

  run:
    desc: Run the server locally
    cmds:
      - go run ./cmd/server

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin

  test:
    desc: Run all tests
    cmds:
      - go test ./... -v
