// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int64
	FeatureID pgtype.Int4
	UserID    pgtype.Text
	Variant   pgtype.Text
	EventType pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Feature struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Active      bool
	CreatedAt   pgtype.Timestamptz
}

type Variant struct {
	ID        int32
	FeatureID pgtype.Int4
	Name      string
	Weight    int32
}
