---
- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Apply pending security upgrades
  ansible.builtin.apt:
    upgrade: safe
  register: system_upgrade

- name: Configure additional apt repositories
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list.d/{{ item.file }}"
    content: "{{ item.repo }}\n"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ system_extra_apt_repos }}"
  loop_control:
    label: "{{ item.file | default(item.repo) }}"
  notify: Refresh apt cache immediately

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ system_base_packages }}"
    state: present
    update_cache: "{{ system_upgrade is changed }}"

- name: Ensure unattended-upgrades service is enabled
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Ensure fail2ban is enabled
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Enable UFW with sane defaults
  community.general.ufw:
    state: enabled

- name: Set UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { policy: deny, direction: incoming }
    - { policy: allow, direction: outgoing }
  loop_control:
    label: "{{ item.direction }}"

- name: Allow essential inbound services
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"

- name: Ensure Ansible remote tmp directory exists
  ansible.builtin.file:
    path: /tmp/.ansible-tmp
    state: directory
    owner: root
    group: root
    mode: "1777"
