---
app_project_root: /opt/splitter
app_runtime_user: splitter
app_runtime_group: "{{ app_runtime_user }}"
app_local_source_path: "{{ playbook_dir | dirname }}"
app_sync_excludes:
  - frontend/
  - .git/
  - node_modules/
  - .env
  - ansible/
  - "*.md"
